#!/bin/bash

cd "$(dirname ${BASH_SOURCE[0]})"/../tmp

if [ -d spark222 ]; then
  echo "Error: tmp/spark222 is found."
  exit 1
fi

if ! which curl > /dev/null; then
  echo "Error: find no curl command in the path"
  exit 1
fi  

rm *.tgz > /dev/null
curl -o spark-2.2.2-bin-hadoop2.7.tgz http://mirrors.ocf.berkeley.edu/apache/spark/spark-2.2.2/spark-2.2.2-bin-hadoop2.7.tgz
curl -o bfg-1.13.0.jar http://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar

tar xzf spark-2.2.2-bin-hadoop2.7.tgz
mv spark-2.2.2-bin-hadoop2.7 spark222
rm spark-2.2.2-bin-hadoop2.7.tgz
